# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AR Education' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AR Education

  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'AR EducationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AR EducationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
